### ISSUE TITLE
Exploratory analysis in vignette

### ISSUE THREAD

**Issue by azheng26** [tito1224/GLMM#7]

**Comment by tito1224** [comment]
added a few more graphs + table - lmk what you think! I don't think we need the data processing part of the .Rmd because we have already put the cleaned data as a .rd file. Using read.csv() on old data would be confusing, esp since the cleaned data is automatically available. Everything else looks good tho!

**Comment by azheng26** [comment]
The assigment asked for data processing in the vignette so I think we should include it! Most exploratory analyses include data cleaning and I feel like we should show how the data is being cleaned. It makes the most sense to me to have it in the vignette instead of hiding it, in case anyone isn't familiar with the cleaned version already!

**Comment by tito1224** [comment]
yes makes sense! i changed up the name of the variables a bit but i think it should work now - lmk if you can run it!

**Comment by azheng26** [comment]
Perfect!
